version: '3'

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  backend:
    build:
      context: ./api
    container_name: backend
    expose:
      - 5000:5000

  frontend:
    build:
      context: ./ui
    container_name: frontend
    expose:
      - 3000:80