version: '3'

services:
  backend:
    build:
      context: ./api
    container_name: backend
    expose:
      - "5000"
    networks:
      - webnet

  frontend:
    build:
      context: ./ui
    container_name: frontend
    expose:
      - "80"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - backend
      - frontend
    networks:
      - webnet

networks:
  webnet: