version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: translator_api
    ports:
      - "5000:5000"

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: translator_ui
    ports:
      - "80:80"